---
pid: /var/vcap/sys/run/acm/acm.pid
name: ACM
port: 9090
logging:
  level: debug
  file: /tmp/acm.log
db:
  database: postgres://acm_user:t9d63703cf6451287540d6@172.23.210.28:2544/acmdb
  max_connections: 10
  pool_timeout: 2000
basic_auth:
  user: acm_user
  password: t9d63703cf6451287540d6

