---
pid: /tmp/acm.pid
name: ACM
port: 9090
logging:
  level: DEBUG
  file: /tmp/acm.log
db:
  database: "sqlite://acm.db"
  max_connections: 32
  pool_timeout: 10
basic_auth:
  user: acm_user
  password: acm_password1234
